site_name: Fynor
site_description: "Fynor is a lightweight Python WSGI framework for learning purposes."
site_url: https://github.com/goldendevuz/fynor
repo_url: https://github.com/goldendevuz/fynor
repo_name: "Fynor"
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Handlers: handlers.md
  - Templates: templates.md
  - Static Files: static.md
  - Exception Handling: exceptions.md
  - Middleware: middleware.md
  - Features: features.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

extra:
  version: 0.1.2
