site_name: Fynor
site_description: "Fynor is a lightweight Python WSGI framework for learning purposes."
site_url: https://github.com/goldendevuz/fynor
repo_url: https://github.com/goldendevuz/fynor
repo_name: "Fynor"
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.tabs
    - toc.integrate
    - palette.toggle

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Handlers: handlers.md
  - Templates: templates.md
  - Static Files: static.md
  - Exception Handling: exceptions.md
  - Middleware: middleware.md
  - Features: features.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

extra:
  version: 0.1.2
  badges:
    python: "https://img.shields.io/badge/python-3.9%2B-blue"
    fynor: "https://img.shields.io/badge/fynor-0.1.2-green"
    jinja2: "https://img.shields.io/badge/Jinja2-3.1.6-orange"
    parse: "https://img.shields.io/badge/parse-1.20.2-red"
    webob: "https://img.shields.io/badge/WebOb-1.8.9-yellow"
    whitenoise: "https://img.shields.io/badge/whitenoise-6.11.0-lightgrey"
    license: "https://img.shields.io/badge/license-MIT-brightgreen"
