name: Deploy Docs

on:
  push:
    # Deploy whenever a tag like v0.1.2, v0.1.3, etc. is pushed
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required to push to gh-pages branch

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions

      # 4️⃣ Build MkDocs site
      - name: Build docs
        run: mkdocs build

      # 5️⃣ Deploy to GitHub Pages using your custom token
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./site
